Pathfinder:
    Dt: 0.01
    ReferenceFrame: "odom/unfiltered" # "odom/unfiltered", "estimated_odom"
    Simulation: "disabled"
    SkipInitialBiasMatrixCalculation: "disabled"  # meant for simulation, where there's no bias introduced

Whiskers:
    BiasNoiseSamples: 10  # Whiskers have some bias and noinse, so the robot takes the given number of samples of the whisker messages at the start to set an offset for the whiskers
    Simulation:
        AddNoise: "disabled"  # "enabled"/"disabled"
        AddSimulatedBias: "disabled"  # "enabled"/"disabled"

Control:
    PID:
        Horizontal:
            Kp: 1
            Ki: 0.5
            Kd: 0.2
            Setpoint: 0.2
            Saturation: [-0.5, 0.5]
        DirectionWall:
            Kp: 7.5
            Ki: 1.5
            Kd: 0.5
            Setpoint: 0
            Saturation: [-5, 5]
        DirectionPath:
            Kp: 0.01
            Ki: 0.002
            Kd: 0.005
            Setpoint: 0
            Saturation: [-40, 40]
