Pathfinder:
    Dt: 0.01
    ReferenceFrame: "odom/unfiltered" # "odom/unfiltered", "estimated_odom"

Whiskers:
    BiasNoiseSamples: 300  # Whiskers have some bias and noise, so the robot takes the given number of samples of the whisker messages at the start to set an offset for the whiskers
    AddNoise: "disabled"
    AddSimulatedBias: "disabled"

Control:
    PID:
        Direction:
            Kp: 2
            Ki: 0
            Kd: 0
            Setpoint: 0
            Saturation: [-20, 20]

        Horizontal:
            Kp: 5
            Ki: 0
            Kd: 0
            Setpoint: 0.2
            Saturation: [-5, 5]

        XAxis:
            Kp: 20
            Ki: 0
            Kd: 0
            Setpoint: 0
            Saturation: [-40, 40]

        XAxisTurning:
            Kp: 40
            Ki: 0
            Kd: 0
            Setpoint: 0
            Saturation: [-40, 40]
