Pilot:
    dt: 0.01
    reference_frame: "odom/unfiltered" # "odom/unfiltered", "estimated_odom"

Control:
    PID:
        Kp: [2.0, 2.0, 2.3]
        Kd: [0.8, 0.8, 0.9]
        Ki: [0.03, 0.03, 0.02]
        windup: [1.0, 1.0, 1.0]
        saturation: [0.7, 0.7, 0.5]
